// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp64jnFMJVhq0eg-62omUHcA02A7Oxjk8',
    appId: '1:95599418351:web:cd0815485296d8be12f41a',
    messagingSenderId: '95599418351',
    projectId: 'wheels-fd8c0',
    authDomain: 'wheels-fd8c0.firebaseapp.com',
    storageBucket: 'wheels-fd8c0.firebasestorage.app',
    measurementId: 'G-6SSG01937Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxoSQ1-LRmW7BUztaEF_e7kOTVE0U6us',
    appId: '1:95599418351:android:875078f41e9da1db12f41a',
    messagingSenderId: '95599418351',
    projectId: 'wheels-fd8c0',
    storageBucket: 'wheels-fd8c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZb1SsRAK9lu68Kx2yLPTgoo8Bz_i3PM',
    appId: '1:95599418351:ios:0e1960e893260d6612f41a',
    messagingSenderId: '95599418351',
    projectId: 'wheels-fd8c0',
    storageBucket: 'wheels-fd8c0.firebasestorage.app',
    iosBundleId: 'com.example.wheels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZb1SsRAK9lu68Kx2yLPTgoo8Bz_i3PM',
    appId: '1:95599418351:ios:0e1960e893260d6612f41a',
    messagingSenderId: '95599418351',
    projectId: 'wheels-fd8c0',
    storageBucket: 'wheels-fd8c0.firebasestorage.app',
    iosBundleId: 'com.example.wheels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp64jnFMJVhq0eg-62omUHcA02A7Oxjk8',
    appId: '1:95599418351:web:8b6a5c840b5d1b0b12f41a',
    messagingSenderId: '95599418351',
    projectId: 'wheels-fd8c0',
    authDomain: 'wheels-fd8c0.firebaseapp.com',
    storageBucket: 'wheels-fd8c0.firebasestorage.app',
    measurementId: 'G-VS60GH0T0Q',
  );
}
